export const projects = {
  software: [
    'router.so',
    'outr.ai',
    'wavefinder.io',
    'swyftfin.com',
    'oat.pics',
    'abstract.ac',
    'penman.surf',
    'pager.dev',
  ],
  open_source: [
    'components.bridger.to',
    'resume.bridger.to',
    'starter.bridger.to',
    'mdx.bridger.to',
    'craft.bridger.to',
    'wp.9d8.dev',
    'pay.9d8.dev',
    'designbooks.org',
  ],
  other: [
    '9d8.dev',
    'wipdes.com',
    'alpinecodex.com',
    'asap.engineering',
    'wip.ac',
    'zion.surf',
    'brijr.dev',
    'bridger.to/youtube',
  ],
}
